stages:
  - build
  - deploy

image: node:16

build-dev:
  tags:
    - spraaksamlingene_01
  stage: build
  script:
  - npm install
  - npm run build
  artifacts:
    expire_in: "1 week"
    paths:
    - .output


deploy-dev:
  tags:
    - spraaksamlingene_01
  stage: deploy
  before_script:
  - eval $(ssh-agent -s)
  - echo "$NUXT_DEV_UBBE" | base64 --decode | ssh-add -

  script:
  - ssh -o StrictHostKeyChecking=no node@158.37.63.144
    "sudo /usr/bin/systemctl stop nuxt-dev.service &&
    whoami &&
    rm -r /node/.output"
  - scp -R .output node@158.37.63.144:/node/.output
  - ssh -o StrictHostKeyChecking=no node@158.37.63.144
    sudo /usr/bin/systemctl start nuxt-dev.service

    
