stages:
  - build
  - deploy

image: node:16

deploy-dev:
  tags:
    - spraaksamlingene_01
  stage: deploy
  when: manual
  before_script:
  - eval $(ssh-agent -s)
  - echo "$NUXT_DEV_UBBE" | base64 --decode | ssh-add -

  script:
  - echo "hello"
  - ssh -o StrictHostKeyChecking=no node@158.37.63.144
    sudo /usr/bin/systemctl stop nuxt-dev.service
