default:
  image: node:18

stages:
  - preview
  - prod


.ordbokene:
  variables:
    VERCEL_ORG_ID: $VERCEL_ORG_ID
    VERCEL_PROJECT_ID: $VERCEL_ORDBOKENE_PROJECT_ID
    VERCEL_TOKEN: $VERCEL_TOKEN_HENRIK
  tags:
    - group_runner_spraaksamlingene_01


ordbokene_preview:
  stage: preview
  extends: .ordbokene
  script:
    - curl -L https://git.app.uib.no/api/v4/projects/16442/jobs/artifacts/vue3-publish/raw/components.tar.gz?job=publish_vue3 | tar xz
    - ls
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN
                    -m gitlabDeployment="1"
                    -m gitlabCommitAuthorName="${CI_COMMIT_AUTHOR}"
                    -m gitlabCommitMessage="${CI_COMMIT_MESSAGE}"
                    -m gitlabCommitOrg="${CI_PROJECT_NAMESPACE}"
                    -m gitlabCommitRef="${CI_COMMIT_REF_NAME}"
                    -m gitlabCommitRepo="ordbokene-nuxt"
                    -m gitlabCommitSha="${CI_COMMIT_SHA}"
                    -m gitlabOrg="https://git.app.uib.no/"
                    -m gitlabRepo="ordbokene-nuxt"
                    -m gitlabCommitAuthorLogin="${GITLAB_USER_LOGIN}"


ordbokene_prod:
  extends: .ordbokene
  stage: prod
  when: manual
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
                    -m gitlabDeployment="1"
                    -m gitlabCommitAuthorName="${CI_COMMIT_AUTHOR}"
                    -m gitlabCommitMessage="${CI_COMMIT_MESSAGE}"
                    -m gitlabCommitOrg="${CI_PROJECT_NAMESPACE}"
                    -m gitlabCommitRef="${CI_COMMIT_REF_NAME}"
                    -m gitlabCommitRepo="ordbokene-nuxt"
                    -m gitlabCommitSha="${CI_COMMIT_SHA}"
                    -m gitlabOrg="https://git.app.uib.no/"
                    -m gitlabRepo="ordbokene-nuxt"
                    -m gitlabCommitAuthorLogin="${GITLAB_USER_LOGIN}"

