default:
  image: node:18

stages:
  - preview
  - prod


.ordbokene:
  variables:
    VERCEL_ORG_ID: $VERCEL_ORG_ID
    VERCEL_PROJECT_ID: $VERCEL_ORDBOKENE_PROJECT_ID
    VERCEL_TOKEN: $VERCEL_TOKEN_HENRIK
  tags:
    - group_runner_spraaksamlingene_01


ordbokene_preview:
  stage: preview
  extends: .ordbokene
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - cat .vercel/project.json
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN
                    -m gitlabDeployment="1"
                    -m gitlabCommitAuthorName="${CI_COMMIT_AUTHOR}"
                    -m gitlabCommitMessage="${CI_COMMIT_MESSAGE}"
                    -m gitlabCommitOrg="${CI_PROJECT_NAMESPACE}"
                    -m gitlabCommitRef="${CI_COMMIT_REF_NAME}"
                    -m gitlabCommitRepo="ordbokene-nuxt"
                    -m gitlabCommitSha="${CI_COMMIT_SHA}"
                    -m gitlabOrg="https://git.app.uib.no/"
                    -m gitlabRepo="ordbokene-nuxt"
                    -m gitlabCommitAuthorLogin="${GITLAB_USER_LOGIN}"
