stages:
  - build
  - deploy

image: node:16

deploy-dev:
  tags:
    - spraaksamlingene_01
  stage: deploy
  when: manual
  script:
  - echo "hello"
  - ssh -o StrictHostKeyChecking=no node@158.37.63.144
    sudo /usr/bin/systemctl stop nuxt-dev.service
